### ISSUE TITLE
Order of sensors is not saved in GSettings

### ISSUE THREAD

**Issue by al3xu5** [mate-desktop/mate-sensors-applet#11]
mate 1.6

Some user's settings in the mate-sensors-applet's preferences are lost starting a new session. 
Lost settings are just those related to the display order of the selected sensors in the panel.

[Updated 2013-04-06]
##

**Comment by monsta** [comment]
I can add to this that running ```killall mate-panel``` (panel restart) also sets sensors order to the default one. Not sure if it's the same issue though.

**Comment by infirit** [comment]
sensors-applet added GSettings now as well but not like it was done in MATE so was not trivial to quickly adapt. My suggestion is to sync with their code [here](http://sourceforge.net/p/sensors-applet/code/ci/34ed8c1cfa6b37b3490cab05885219de3aaacda1/)

**Comment by acrobat1** [comment]
I'm having the exact same issue in MATE 1.10 as well : sensor's  order is lost at every reboot, it  always reverts to hdd/video card/cpu sensors (left to right) .
It happens with MATE 1.8 as well in the exact same way, but it didn't happen (in my case) with MATE 1.6 and earlier.

I also have a problem with reported hdd temperatures varying randomly, no matter which corrections I try the values will again be off at every reboot, this has been happening in 1.6 too: should I open a separate issue for this?

**Comment by monsta** [comment]
> I also have a problem with reported hdd temperatures varying randomly, no matter which corrections I try the values will again be off at every reboot, this has been happening in 1.6 too: should I open a separate issue for this?

Yes, it's a separate issue related to hdd backend.

**Comment by acrobat1** [comment]
I've installed MATE 1.8

`mate-desktop1.8.1+dfsg1-1~bpo70+1
mate-desktop-environment	  1.8.0+7~bpo70+1`

 in Debian 7 trough Debian backports and oddly enough this issue doesn't happen: I have cpu and hdd sensors all in the right place and hdd temperatures are correct.

This is the first time for me since MATE 1.6 that I'm not seeing  this issue (on the same hardware), I have no clue about to why it is working.

**Comment by info-cppsp** [comment]
Please merge this issue to #46 and close it.
See my comments there.
I may be able to figure it out.
https://github.com/mate-desktop/mate-sensors-applet/issues/46
