### ISSUE TITLE
Poor layout when using on a left or right panel

### ISSUE THREAD

**Issue by baryluk** [mate-desktop/mate-sensors-applet#126]
![Screenshot at 2021-11-20 14-00-54](https://user-images.githubusercontent.com/110322/142729062-660273b3-16ec-4757-aac9-bb230dbe3321.png)

As you can see, the icons are not centered on the panel properly.

If you enable a fan speed (i.e. 1324 RPM), it becomes even worse:

![Screenshot at 2021-11-20 14-02-16](https://user-images.githubusercontent.com/110322/142729093-c9726217-f16e-4842-af9a-9d600e0e961c.png)

#### MATE general version
1.24 from Debian testing

**Comment by raveit65** [comment]
You need to increase panel size.
Icons and text are exactly centered.
![sensors-applet](https://github.com/mate-desktop/mate-sensors-applet/assets/961604/96cd820a-8000-4c8d-a3fc-02ec07c9b845)
