### ISSUE TITLE
mate-sensors-applet-1.10.3 regression

### ISSUE THREAD

**Issue by alxpl** [mate-desktop/mate-sensors-applet#34]
Hi,

The sensors applet segfaults on Fedora 22 on a Lenovo g50-30 laptop. I have tried both the package in the repos as well as another provided by Wolfgang. This is from my journal and it was collected during two consecutive attempts to add the applet to the panel - apparently the problem lies with libhddtemp.so:

`Jul 20 18:32:17 <redacted> /usr/libexec/gdm-x-session[1812]: Activating service name='org.mate.panel.applet.SensorsAppletFactory'`
`Jul 20 18:32:17 <redacted> /usr/libexec/gdm-x-session[1812]: Successfully activated service 'org.mate.panel.applet.SensorsAppletFactory'`
`Jul 20 18:32:17 <redacted> audit[3104]: <audit-1701> auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3104 comm="mate-sensors-ap" exe="/usr/libexec/mate-sensors-applet" sig=11`
`Jul 20 18:32:17 <redacted> kernel: show_signal_msg: 33 callbacks suppressed`
`Jul 20 18:32:17 <redacted> kernel: mate-sensors-ap[3104]: segfault at 0 ip 00007ff2b6df0de7 sp 00007ffe23d224a0 error 6 in libhddtemp.so[7ff2b6df0000+2000]`
`Jul 20 18:32:18 <redacted> /usr/libexec/gdm-x-session[1812]: ** (mate-panel:1995): WARNING **: Operation was cancelled`
`Jul 20 18:32:18 <redacted> /usr/libexec/gdm-x-session[1812]: ** (mate-panel:1995): WARNING **: Operation was cancelled`
`Jul 20 18:32:18 <redacted> abrt-server[3108]: Deleting problem directory ccpp-2015-07-20-18:32:17-3104 (dup of ccpp-2015-07-19-22:59:48-2511)`
`Jul 20 18:32:19 <redacted> dbus[799]: [system] Activating service name='org.freedesktop.problems' (using servicehelper)`
`Jul 20 18:32:19 <redacted> dbus[799]: [system] Successfully activated service 'org.freedesktop.problems'`
`Jul 20 18:32:19 <redacted> abrt-server[3108]: Lock file '.lock' is locked by process 3115`
`Jul 20 18:32:22 <redacted> /usr/libexec/gdm-x-session[1812]: Activating service name='org.mate.panel.applet.SensorsAppletFactory'`
`Jul 20 18:32:22 <redacted> /usr/libexec/gdm-x-session[1812]: Successfully activated service 'org.mate.panel.applet.SensorsAppletFactory'`
`Jul 20 18:32:22 <redacted> audit[3120]: <audit-1701> auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3120 comm="mate-sensors-ap" exe="/usr/libexec/mate-sensors-applet" sig=11`
`Jul 20 18:32:22 <redacted> kernel: mate-sensors-ap[3120]: segfault at 0 ip 00007f1d2b1b8de7 sp 00007fffff20ab30 error 6 in libhddtemp.so[7f1d2b1b8000+2000]`
`Jul 20 18:32:22 <redacted> abrt-hook-ccpp[3123]: Not saving repeating crash in '/usr/libexec/mate-sensors-applet'`
`Jul 20 18:32:22 <redacted> /usr/libexec/gdm-x-session[1812]: ** (mate-panel:1995): WARNING **: Operation was cancelled`
`Jul 20 18:32:22 <redacted> /usr/libexec/gdm-x-session[1812]: ** (mate-panel:1995): WARNING **: Operation was cancelled`

Let me know if you need anything else.

**Comment by infirit** [comment]
mea culpa, 5cab0e83ac2f44fe78ba6ef1732a3286ec3f9476 fixes this.
