### ISSUE TITLE
[1.18] mate sensors applet dont respect its position.

### ISSUE THREAD

**Issue by javashin** [mate-desktop/mate-sensors-applet#41]
hello the mate-sensors-applet-1.18.0 is not showing in the correct place in the mate panel i installed just with configure --prefix=/usr and i had to downgrade to the 1.16.0 version in order to make it work like it has to be here is a screenshot in the correct place with old verision inside full mate 1.18
![screenshot at 2017-03-14 20-59-22](https://cloud.githubusercontent.com/assets/15115613/23928972/50e1cad6-08f9-11e7-9129-6ed4a3833e11.png)

**Comment by javashin** [comment]
and here is the mate-sensors-applet 1.18.0 in a way other level with the same configuration as the other screenshot 
![screenshot at 2017-03-14 21-03-32](https://cloud.githubusercontent.com/assets/15115613/23929082/e56ebf24-08f9-11e7-974f-705858e3365b.png)

**Comment by javashin** [comment]
this is gentoo with mate 1.18 gtk3 all compiled with:
CFLAGS="-march=westmere -mtune=westmere -O2 -pipe -fstack-protector-strong"
everything is working like it has to be only mate-sensors applet have this issue so far . thanks in advance.

**Comment by flexiondotorg** [comment]
I don't know what you're trying to describe here? I can't see any obvious problem when comparing the two screenshots.

**Comment by javashin** [comment]
cool

**Comment by monsta** [comment]
Confirmed. Looks like a regression from 0392b7a56d88153f5305bf2c50c8cb958572ee9f. :disappointed:

**Comment by raveit65** [comment]
We need to set valign=GTK_ALIGN_CENTER to the whole GtkGrid, than every sensor is in the middle of the panel. The default GTK_ALIGN_FILL isn't useful here.
You can test this in runtime with gtk3-inspector and set up this in inspectors properties page for the grid.
I guess for a vertical panel we need halign=GTK_ALIGN_CENTER.

**Comment by lukefromdc** [comment]
confirmed

**Comment by monsta** [comment]
@javashin: fixed in https://github.com/mate-desktop/mate-sensors-applet/commit/6dd3a48122004ac8bec2264ac513a6e2b7b760a1, you can make a patch from that commit (we will release 1.18.1 later).
