### ISSUE TITLE
Graphs Invisible (may be present but greyscale)

### ISSUE THREAD

**Issue by glimmung** [mate-desktop/mate-sensors-applet#45]
On a current Ubuntu Mate version, selecting a graph for a given sensor is ineffective.

Peering very closely at the screen, it seems that the graph may be there but in shades of grey so close as to be indistinguishable
![selection_044-zoomed](https://cloud.githubusercontent.com/assets/1511399/26800992/2b5aa83e-4a33-11e7-948d-184b9edfd1a4.jpg)
 (tested on multiple machines to sanity-check)

**Comment by BenLand100** [comment]
I'm seeing the same thing on version 1.18.2. Initially I thought this might be theme related but that seems not to be the case.

**Comment by info-cppsp** [comment]
changing the bg color from black to white reveals that the graphs are drawn in black
active-sensors.c l279
cairo_set_source_rgb(cr, 0.0, 0.0, 0.0); -> cairo_set_source_rgb(cr, 1.0, 1.0, 1.0);

**Comment by info-cppsp** [comment]
in active-sensors.c
lines 314,315,316, 320,321,322 have a division (/ 65535.0).
this is not needed.
[color.txt](https://github.com/mate-desktop/mate-sensors-applet/files/1274093/color.txt)

here is a diff -u patch

**Comment by info-cppsp** [comment]
I have tried to follow this:
http://wiki.mate-desktop.org/contribute
I hope I did everything right.
Please review and merge.

**Comment by monsta** [comment]
Ok, fixed by https://github.com/mate-desktop/mate-sensors-applet/pull/49.

**Comment by monsta** [comment]
The fix is now released in version 1.18.3.
