### ISSUE TITLE
Color on Linux Mate 18.2 Sonya 64b

### ISSUE THREAD

**Issue by Spirou4D** [mate-desktop/mate-sensors-applet#61]
#### Expected behaviour
The color don't run on the sensors!!! Red setup but only grey!
http://storage8.static.itmages.com/i/17/1218/h_1513613494_7263891_98f16ea6f6.jpeg

#### MATE general version
1.18.0

#### Package version
Noyau Linux 4.8.0-53-generic x86_64

#### Linux Distribution
Mint 18.2 Sonya 64b

**Comment by info-cppsp** [comment]
corrected by PR #49 
It is in the 1.18.3 version of msa.
Please update.

**Comment by Spirou4D** [comment]
Thanks!
All is ok now! Byebye
