### ISSUE TITLE
Fix GtkStock deprecated make warnings

### ISSUE THREAD

**Issue by info-cppsp** [mate-desktop/mate-sensors-applet#66]
As per title.
Useful links:
https://docs.google.com/document/d/1KCVPoYQBqMbDP11tHPpjW6uaEHrvLUmcDPqKAppCY8o/pub
https://docs.google.com/spreadsheets/d/1HavJQRPpMuq-N0GoN1wJR-9KEGXpKy3-NEPpZZkUGJY/pub?output=html

I'm already on it.

**Comment by raveit65** [comment]
see my comment in PR

**Comment by info-cppsp** [comment]
Yeah, next time I'll only make a PR...
