### ISSUE TITLE
V1.2

### ISSUE THREAD

**Issue by Ntemis** [mate-desktop/mate-sensors-applet#76]
#### Expected behaviour
To show hdd temps

#### Actual behaviour
even if i have a 
![screenshot at 2018-02-10 18-11-10](https://user-images.githubusercontent.com/2123893/36064047-f1556348-0e8d-11e8-8179-f59f31e843b2.png)
They aren't actually been used 

shows only cpu temp
#### Steps to reproduce the behaviour
you know

#### MATE general version
1.20

#### Package version

dpkg whatever
#### Linux Distribution
xenial 16.04.3

#### Link to downstream report of your Distribution
have no idea what this is

**Comment by info-cppsp** [comment]
![screenshot at 2018-02-10 17-24-25](https://user-images.githubusercontent.com/31438307/36064187-6a3ad614-0e87-11e8-9c85-a1feeef8b15b.png)

?

**Comment by raveit65** [comment]
Sorry, we don't support Mate-1.2 any more,  since several years.
Actual version is mate-1.20.
So, file out a report against your distro and ask distro maintainer to fix that, or use a distro with actual Mate version.

**Comment by raveit65** [comment]
What is so hard to post correct package versions for an ubuntu release?

**Comment by Ntemis** [comment]
Ah sorry about this i was missing/failed to see there was an enable tick box on my 4k monitor lol
Thanks
